name: Run Jest Tests
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: goprUavOpsManager

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: goprUavOpsManager/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        run: npm test -- --ci --runInBand
